### PR TITLE
Various Bug Fixes

### PR DESCRIPTION
**Pull request by Fear-MK**
## Description
Completed Squad Queue issue (untested), Predict command issue (along with removal of URL shorten code) (untested), and formatting issues with lists in commands (tested) 
## Checklist

- [ ] If code changes were made, they have been tested
- [X] This PR fixes an issue
- [ ] This PR is not a code change (ie. documentation, typehinting, comments, etc.)

### CODE REVIEW

**Comment by Fear-MK** [comment]
I DONT KNOW HOW TO FIX THE REVIEW SHIT, MAYBE UH WRITE SOME CODE TO DO IT YOURSELF LOL

**Comment by BadWolf1023** [comment]
@Fear-MK **You need to see your VS to use LF character return**. As a courtesy, I will fix your PR for you. Please ensure this in the future.

**Comment by Fear-MK** [comment]
Was sure that I did that, even prompted me to save the files after changing it to LF. However next time I will set it before I start editing.

**Comment by BadWolf1023** [comment]
After fixing the issue, this PR doesn't seem to address the issues in your description. Please check to make sure you have committed the correct files, then reopen this PR.

**Pull request closed without merging**
